# Generated by Django 3.1.7 on 2023-02-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='description',
        ),
    ]
