# Generated by Django 3.1.7 on 2023-02-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipcrtype',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
