# Generated by Django 3.1.7 on 2023-02-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0002_remove_ipcr_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_1',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 1'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_2',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 2'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_3',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 3'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_4',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 4'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_5',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 5'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_6',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 6'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_7',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 7'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_mfo_pap_8',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra MFO/PAP row 8'),
        ),
    ]
