# Generated by Django 3.1.7 on 2023-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0003_auto_20230210_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='stra_percentage',
            field=models.CharField(default='', max_length=255, verbose_name='Strategic Function Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_sucess_indicators_1',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Stra Sucess Indecator row 1'),
        ),
    ]
